force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>hud_DEPT_ID__c</fullName>
        <externalId>true</externalId>
        <label>hud_DEPT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Error_Log__c.object
<CustomObject>
    <description>Record the errors in the running.  Then you can set up a workflow on the error log object to send email whenever a new error log is created.</description>
    <label>Error_Log</label>
    <nameField>
        <label>Error_Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error_Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>EmailReceiver__c</fullName>
        <label>EmailReceiver</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Trace__c</fullName>
        <description>Log the details of the error.</description>
        <inlineHelpText>Developers call this class to record the details of the error in the running time.</inlineHelpText>
        <label>Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

force-app/main/default/objects/hed__Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>hud_DEPT_ID__c</fullName>
        <externalId>true</externalId>
        <label>hud_DEPT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hud_MULE_UNIQUE_PERSON_KEY__c</fullName>
        <externalId>true</externalId>
        <label>hud_MULE_UNIQUE_PERSON_KEY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
</CustomObject>

main/default/classes/HED_AffiliationsUpdateByAccountsBatch.cls
global class HED_AffiliationsUpdateByAccountsBatch implements Database.Batchable<sObject>{
public String email;


global Database.querylocator start(Database.BatchableContext BC){
       return Database.getQueryLocator([SELECT id, hud_MULE_UNIQUE_PERSON_KEY__c, hed__Contact__c, hud_DEPT_ID__c, hed__Account__c from hed__Affiliation__c where hud_DEPT_ID__c !=null]);}

global void execute(Database.BatchableContext BC, List<hed__Affiliation__c> scope){
	 try{
		List<hed__Affiliation__c> toUpdate = new List<hed__Affiliation__c>();
        
        Set<String> myKeys = new Set<String>();
        for (hed__Affiliation__c a : scope) {
            myKeys.add(a.hud_DEPT_ID__c);
        }
        
        Account[] allAccountObjs = [select id, hud_DEPT_ID__c from Account where hud_DEPT_ID__c in :myKeys];
       
       
		for(hed__Affiliation__c myRecord : scope){
			
			 boolean matchedBefore = false;
			 
            // filter allAccountObjs to ones for just this hed__Affiliation__c
            List<Account> accountObjs = new List<Account>();
            for (Account e : allAccountObjs) {
                if (e.hud_DEPT_ID__c == myRecord.hud_DEPT_ID__c) {
                    accountObjs.add(e);
                }
            }
            
             if(accountObjs!=null && !accountObjs.isEmpty()) {
                for(Account myObj: accountObjs) {
                	//no change
                    if (myRecord.hud_DEPT_ID__c !=null && myRecord.hed__Account__c !=null && myRecord.hed__Account__c == myObj.id){
                        matchedBefore = true;                        
                    } else {
                        myRecord.hed__Account__c = myObj.id;
                        toUpdate.add(myRecord);
                    }
                }         
            }
	    }
	    update toUpdate;
     }
    catch (Exception e) {  
            
                HUD_GlobalVariables myGlobal = new HUD_GlobalVariables();
            
                Error_Log__c log = new Error_Log__c();
                
                log.EmailReceiver__c = myGlobal.getEmailAlertEmailbox();
            
                log.trace__c = 'Type: ' + e.getTypeName() + '\n' + 'Cause: ' + e.getCause() + '\n' + 'Message: ' 
            
                + e.getMessage() + '\n' + 'Line #: ' + e.getLineNumber() + '\n' + e.getStackTraceString() + '\n'
            
                + 'Class Name: ' + 'HED_AffiliationsUpdateByContactsBatch';
            
                insert log;   
            
    }
}

global void finish(Database.BatchableContext BC){
	//Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	
	//mail.setToAddresses(new String[] {email});
	//mail.setReplyTo('batch_notification_SF@harvard.edu');
	//mail.setSenderDisplayName('Batch Processing');
	//mail.setSubject('Batch Process Completed');
	//mail.setPlainTextBody('Batch Process has completed');
	
	//Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
}
}