force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>hud_MULE_UNIQUE_PERSON_KEY__c</fullName>
        <externalId>true</externalId>
        <label>hud_MULE_UNIQUE_PERSON_KEY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/hud_Location__c.object
<CustomObject>
    <label>hud_Location</label>
    <nameField>
        <displayFormat>HLO-{00000000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>hud_Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Location_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>hud_Locations</relationshipLabel>
        <relationshipName>hud_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MULE_UNIQUE_PERSON_KEY__c</fullName>
        <externalId>true</externalId>
        <label>MULE_UNIQUE_PERSON_KEY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
</CustomObject>

main/default/classes/HUDLocationsUpdateByContacts_Test.cls
@isTest(seeAllData=false)
private class HUDLocationsUpdateByContacts_Test {

  public static List<Contact> contactsList;
  public static List<hud_Location__c> LocationsList;
  public static String MULE_KEY;
  public static HUDLocationsUpdateByContacts myMethod;
   
  static void init(){
     myMethod = new HUDLocationsUpdateByContacts();
     contactsList = new List<Contact>();
     LocationsList = new List<hud_Location__c>();
     MULE_KEY = 'abcdefg';
     LocationsList.add(new hud_Location__c(
           MULE_UNIQUE_PERSON_KEY__c = MULE_KEY
     ));
  }

  /** Test with creating an Location object first and then creating a contact after **/
  static testMethod void test() {
     init();
     Test.startTest();
     
     
     
     insert LocationsList;
     
     contactsList.add(new Contact(
         hud_MULE_UNIQUE_PERSON_KEY__c = MULE_KEY,
         Lastname = 'Smith'
     ));
     insert contactsList;
     
     myMethod.runUpdate();
     
     // Getting the hud_Address to verify that the ‘Location_Contact__c’ field is not null
     LocationsList = [
         SELECT Id, Location_Contact__c
         FROM hud_Location__c
         WHERE Id =:LocationsList[0].Id
     ];
     
     // Verification
     System.assertEquals(LocationsList[0].Location_Contact__c, contactsList[0].Id);
     
     Test.stopTest();
  }
   
    
  
  
}