force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>hud_MULE_UNIQUE_PERSON_KEY__c</fullName>
        <externalId>true</externalId>
        <label>hud_MULE_UNIQUE_PERSON_KEY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/hud_Location__c.object
<CustomObject>
    <label>hud_Location</label>
    <nameField>
        <displayFormat>HLO-{00000000}</displayFormat>
        <label>Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>hud_Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Location_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>hud_Locations</relationshipLabel>
        <relationshipName>hud_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MULE_UNIQUE_PERSON_KEY__c</fullName>
        <externalId>true</externalId>
        <label>MULE_UNIQUE_PERSON_KEY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
</CustomObject>

main/default/classes/HUDLocationsUpdateByContacts.cls
/*

*/
public class HUDLocationsUpdateByContacts {

   public HUDLocationsUpdateByContacts()
   {
   }

   public integer runUpdate() {
        integer count=0; 
        
        hud_Location__c[] recordsLocation = [select id, MULE_UNIQUE_PERSON_KEY__c, Location_Contact__c from hud_Location__c where Location_Contact__c=null limit 99];
     	
     	
        if(recordsLocation!=null && !recordsLocation.isEmpty()) {
            for(hud_Location__c myRecord: recordsLocation) {
                Contact[] contacts = [select id from Contact where hud_MULE_UNIQUE_PERSON_KEY__c = :myRecord.MULE_UNIQUE_PERSON_KEY__c limit 1];
                if(contacts!=null && !contacts.isEmpty() && myRecord.MULE_UNIQUE_PERSON_KEY__c!=null) {
                    for(Contact myContact: contacts) {
                        myRecord.Location_Contact__c=myContact.id;
                        //update myRecord;
                        count ++;
                    }
                }
     
            }
            update recordsLocation;
        }
       
        
        /*
	    //mapping contact
	    for (List<hud_Location__c> records:
	    [SELECT id, MULE_UNIQUE_PERSON_KEY__c, Location_Contact__c from hud_Location__c where Location_Contact__c=null limit 99]) {
	    	update records;    //calling trigger
	        count = records.size();
	    }
	    */
	      
	     return count;
   } 
   

}