force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>hud_MULE_UNIQUE_PERSON_KEY__c</fullName>
        <externalId>true</externalId>
        <label>hud_MULE_UNIQUE_PERSON_KEY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/hud_Phone__c.object
<CustomObject>
    <label>hud_Phone</label>
    <nameField>
        <displayFormat>HPH-{00000000}</displayFormat>
        <label>Phone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>hud_Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>MULE_UNIQUE_PERSON_KEY__c</fullName>
        <externalId>true</externalId>
        <label>MULE_UNIQUE_PERSON_KEY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phone Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>hud_Phones</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/HUDPhonesUpdateByContacts.cls
/*

*/
public class HUDPhonesUpdateByContacts {

   public HUDPhonesUpdateByContacts()
   {
   }

   public integer runUpdate() {
   	 integer count=0; 
   	 
       
        Hud_Phone__c[] recordsPhone = [select id, MULE_UNIQUE_PERSON_KEY__c, Phone_Contact__c from hud_Phone__c where Phone_Contact__c=null limit 99];
        
     
        if(recordsPhone!=null && !recordsPhone.isEmpty()) {
            for(hud_Phone__c myRecord: recordsPhone) {
                Contact[] contacts = [select id from Contact where hud_MULE_UNIQUE_PERSON_KEY__c = :myRecord.MULE_UNIQUE_PERSON_KEY__c];
                if(contacts!=null && !contacts.isEmpty() && myRecord.MULE_UNIQUE_PERSON_KEY__c!=null) {
                    for(Contact myContact: contacts) {
                        myRecord.Phone_Contact__c=myContact.id;
                        //update myRecord;
                        count ++;
                    }
                }
     
            }
            update recordsPhone;
        }
       
        
       
        /*
	    //mapping contact
	    for (List<hud_Phone__c> records:
	    [SELECT id, MULE_UNIQUE_PERSON_KEY__c, Phone_Contact__c from hud_Phone__c where Phone_Contact__c=null limit 99]) {
	    	update records;    //calling trigger
	        count = records.size();
	    }
	    */
	      
	     return count;
        
   } 
   

}