force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>hud_MULE_UNIQUE_PERSON_KEY__c</fullName>
        <externalId>true</externalId>
        <label>hud_MULE_UNIQUE_PERSON_KEY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/hud_Address__c.object
<CustomObject>
    <description>Address object aligned with SF Harvard University Data Architecture.
This differs from HEDA in that it is many to one off of Contact, while HEDA is many to one off of Account.
HUDA strives to represent the relationships as they exist in the systems of record</description>
    <label>hud_Address</label>
    <nameField>
        <displayFormat>HAD-{00000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>hud_Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Address_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>hud_Addresses</relationshipLabel>
        <relationshipName>hud_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MULE_UNIQUE_PERSON_KEY__c</fullName>
        <externalId>true</externalId>
        <label>MULE_UNIQUE_PERSON_KEY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/HUDAddressesUpdateByContacts_Test.cls
@isTest(seeAllData=false)
private class HUDAddressesUpdateByContacts_Test {

  public static List<Contact> contactsList;
  public static List<hud_Address__c> addressesList;
  public static String MULE_KEY;
  public static HUDAddressesUpdateByContacts myMethod;
   
  static void init(){
     myMethod = new HUDAddressesUpdateByContacts();
     contactsList = new List<Contact>();
     addressesList = new List<hud_Address__c>();
    MULE_KEY = 'abcdefg';
    addressesList.add(new hud_Address__c(
           MULE_UNIQUE_PERSON_KEY__c = MULE_KEY
     ));
  }

  /** Test with creating an address object first and then creating a contact after **/
  static testMethod void test() {
     init();
     Test.startTest();
     
     
     
     insert addressesList;
     
     contactsList.add(new Contact(
         hud_MULE_UNIQUE_PERSON_KEY__c = MULE_KEY,
         LastName = 'Smith'
     ));
     insert contactsList;
     
     myMethod.runUpdate();
     
     // Getting the hud_Address to verify that the ‘Address_Contact__c’ field is not null
     addressesList = [
         SELECT Id, Address_Contact__c
         FROM hud_Address__c
         WHERE Id =:addressesList[0].Id
     ];
     
     // Verification
     System.assertEquals(addressesList[0].Address_Contact__c, contactsList[0].Id);
     //System.assertEquals(addressesList[0].Address_Contact__c, null);
     
     Test.stopTest();
  }
   
    
  
  
}