force-app/main/default/objects/Error_Log__c.object
<CustomObject>
    <description>Record the errors in the running.  Then you can set up a workflow on the error log object to send email whenever a new error log is created.</description>
    <label>Error_Log</label>
    <nameField>
        <label>Error_Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error_Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>EmailReceiver__c</fullName>
        <label>EmailReceiver</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Trace__c</fullName>
        <description>Log the details of the error.</description>
        <inlineHelpText>Developers call this class to record the details of the error in the running time.</inlineHelpText>
        <label>Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

force-app/main/default/classes/HUDJobSelfScheduleNameToUpdateAccount.cls
/*
Scheduled job for updating the name of the account by related contact's last name

*/
@Deprecated
global class HUDJobSelfScheduleNameToUpdateAccount implements Schedulable {
  // public static String CRON_EXP = '0 01 * * * ?';

   global void execute( SchedulableContext SC )
        {        
      try{
           //calling batch process
           HUDNameToUpdateAccountsBatch myObj = new HUDNameToUpdateAccountsBatch ();
           myObj.email='HUIT_Salesforce@harvard.edu';
           ID batchprocessid = Database.executeBatch(myObj);
           
           /*
           //start another new job
           HUDJobSelfScheduleNameToUpdateContact.start();

            // abort me and start again
            System.abortJob( SC.getTriggerId() );
            */
            }

      catch (Exception e) {  
      
           HUD_GlobalVariables myGlobal = new HUD_GlobalVariables();
            
           Error_Log__c log = new Error_Log__c();
                
           log.EmailReceiver__c = myGlobal.getEmailAlertEmailbox();
      
          log.trace__c = 'Type: ' + e.getTypeName() + '\n' + 'Cause: ' + e.getCause() + '\n' + 'Message: ' 
      
          + e.getMessage() + '\n' + 'Line #: ' + e.getLineNumber() + '\n' + e.getStackTraceString() + '\n'
      
          + 'Class Name: ' + 'HUDJobSelfScheduleNameToUpdateAccount in scheduled job';
      
          insert log;   
      
      }
        }

        public static void start()
        {
        /*
            // start keepalive again in 1200 seconds
            Datetime sysTime = System.now().addSeconds( 1200 );      
            String chronExpression = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' + sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' + sysTime.year();
            System.schedule( 'HUDJobSelfScheduleNameToUpdateAccount ' + sysTime, chronExpression, new HUDJobSelfScheduleNameToUpdateAccount() );
            */
        }

}