force-app/main/default/objects/GlobalVariable__c.object
<CustomObject>
    <description>This custom object will contain global variables being used in the organization.</description>
    <label>GlobalVariable</label>
    <nameField>
        <label>Global Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GlobalVariables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Value__c</fullName>
        <description>The value for this group variable.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/hud_Email__c.object
<CustomObject>
    <label>hud_Email</label>
    <nameField>
        <displayFormat>HEM-{00000000}</displayFormat>
        <label>Email Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>hud_Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>EFF_STATUS__c</fullName>
        <label>EFF_STATUS</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMAIL_ADDRESS__c</fullName>
        <label>EMAIL_ADDRESS</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Email Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>hud_Emails</relationshipLabel>
        <relationshipName>hud_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OFFICIAL_EMAIL_INDICATOR__c</fullName>
        <label>OFFICIAL_EMAIL_INDICATOR</label>
        <length>1</length>
        <type>Text</type>
    </fields>
</CustomObject>

main/default/classes/HedJobContactEmailUpdate_Test.cls
/**
 
 */
@isTest
private class HedJobContactEmailUpdate_Test {
  public static List<Contact> contactsList;
 
  public static List<hud_Email__c> emailsList;
 
  public static Contact_EmailField_Update_Batch myTestClass;
  
  
  static void init(){
     
    contactsList = new List<Contact>();
    
    emailsList = new List<hud_Email__c>();
    
  }

  /** Test with creating an Location object first and then creating a contact after **/
  static testMethod void test() {
     init();
     Test.startTest();
     
     contactsList.add(new Contact(
        FirstName = 'Mary',
        LastName = 'Jane',
    Email = 'dev@harvard.edu'
    ));
    insert contactsList;
    
    
    emailsList.add(new hud_Email__c(
        Email_Contact__c = contactsList[0].Id,
        Email_address__c = 'test@harvard.edu',
        OFFICIAL_EMAIL_INDICATOR__c = '1',
        EFF_Status__c = '1'
    ));
   insert emailsList;
   
    GlobalVariable__c myVari = new GlobalVariable__c();
       myVari.name = 'Email Address for Email Alerts';
       myVari.value__c = 'test_receiver@harvard.edu';
       insert myVari;
   
   
  
   
   
    //testing scheduling part
      // Schedule a sccheduled job
       String jobId = System.schedule('TestHedJobContactEmailUpdate',
            HedJobContactEmailUpdate.CRON_EXP, 
            new HedJobContactEmailUpdate());

      // Get the information from the CronTrigger API object
      CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
         NextFireTime
         FROM CronTrigger WHERE id = :jobId];

      // Verify the expressions are the same
      System.assertEquals(HedJobContactEmailUpdate.CRON_EXP, 
         ct.CronExpression);

      // Verify the job has not run
      System.assertEquals(0, ct.TimesTriggered);
     
     Test.stopTest();
     
     
     
     contactsList = [
         SELECT Id, Email
         FROM Contact
         WHERE Id =:contactsList[0].Id
     ];
     
     
     
     // Verification     
     System.assertEquals(contactsList[0].Email,'dev@harvard.edu');
   }
}