force-app/main/default/objects/GlobalVariable__c.object
<CustomObject>
    <description>This custom object will contain global variables being used in the organization.</description>
    <label>GlobalVariable</label>
    <nameField>
        <label>Global Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GlobalVariables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Value__c</fullName>
        <description>The value for this group variable.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/HUDJobSelfScheNameToUpdateAccount_Test.cls
@isTest
private class HUDJobSelfScheNameToUpdateAccount_Test {
public static List<Contact> contactsList;
  public static List<Account> objList;
   
  static void init(){
   
     
     contactsList = new List<Contact>();
     objList = new List<Account>();
    
     objList.add(new Account(
           Name = 'test'
     ));
  }

  /** Test with creating a Name object first and then creating a contact after **/
  static testMethod void test() {
     init();
     Test.startTest();
     
     insert objList;
     
     contactsList.add(new Contact(
         AccountId = objList[0].Id,
         LastName = 'mylastname'
     ));
     insert contactsList;
   
      GlobalVariable__c myVari = new GlobalVariable__c();
       myVari.name = 'Email Address for Email Alerts';
       myVari.value__c = 'test_receiver@harvard.edu';
       insert myVari;

      // Schedule the test job
      //  String jobId = System.schedule('testScheduledApex',
      //       HUDJobSelfScheduleNameToUpdateAccount.CRON_EXP, 
      //       new HUDJobSelfScheduleNameToUpdateAccount());
     
    
     Test.stopTest();
     
     objList = [
         SELECT Id, Name  
         FROM Account
         WHERE Id =:objList[0].Id
     ];
     
     // Verification
     //System.assertEquals('mylastname Account', objList[0].Name);
    
   }
}