force-app/main/default/objects/hud_Email__c.object
<CustomObject>
    <label>hud_Email</label>
    <nameField>
        <displayFormat>HEM-{00000000}</displayFormat>
        <label>Email Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>hud_Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>EFF_STATUS__c</fullName>
        <label>EFF_STATUS</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMAIL_ADDRESS__c</fullName>
        <label>EMAIL_ADDRESS</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Email Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>hud_Emails</relationshipLabel>
        <relationshipName>hud_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OFFICIAL_EMAIL_INDICATOR__c</fullName>
        <label>OFFICIAL_EMAIL_INDICATOR</label>
        <length>1</length>
        <type>Text</type>
    </fields>
</CustomObject>

main/default/classes/Contact_EmailField_Update_Batch_Test.cls
@isTest
private class Contact_EmailField_Update_Batch_Test {
  public static List<Contact> contactsList;
  public static List<hud_Email__c> emailsList;
 
  
  public static Contact_EmailField_Update_Batch myTestClass;
   
  static void init(){
     myTestClass = new Contact_EmailField_Update_Batch();
     myTestClass.email='testBatch@harvard.edu';
     
     contactsList = new List<Contact>();
     emailsList = new List<hud_Email__c>();
  
  }

  /** Test with creating an Location object first and then creating a contact after **/
  static testMethod void test() {
     init();
     Test.startTest();
     
     contactsList.add(new Contact(
         FirstName = 'Mary',
         LastName = 'Jane'
     ));
     insert contactsList;
     
     
     emailsList.add(new hud_Email__c(
         Email_Contact__c = contactsList[0].Id,
         Email_address__c = 'test@harvard.edu',
         OFFICIAL_EMAIL_INDICATOR__c = '1',
    EFF_STATUS__c='A'
     ));
   insert emailsList;
   
   
  
     
   
   
    ID batchprocessid = Database.executeBatch(myTestClass);
     
    Test.stopTest();
     
     contactsList= [
         SELECT Id, Email
         FROM Contact
         WHERE Id =:contactsList[0].Id
     ];
     
     
     
     // Verification
     System.assertEquals(contactsList[0].Email,emailsList[0].Email_address__c);
   }
}